# Generated by Django 5.2 on 2025-04-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Header', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
