# Generated by Django 5.2 on 2025-04-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Header', '0002_usuario_codigo_verificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula_encriptada',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
