# Generated by Django 5.2 on 2025-04-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Header', '0003_alter_usuario_cedula_encriptada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula_encriptada',
            field=models.BinaryField(unique=True),
        ),
    ]
