# Generated by Django 5.2 on 2025-04-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Header', '0005_alter_usuario_cedula_encriptada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cedula_encriptada',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
