# Generated by Django 5.2 on 2025-04-20 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Header', '0006_remove_usuario_cedula_encriptada_usuario_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='clasificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Header.clasificacion'),
        ),
    ]
