# Generated by Django 5.2 on 2025-05-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Header', '0007_alter_empresa_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ciudad',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='provincia',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
