# Generated by Django 5.2 on 2025-06-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Header', '0008_empresa_ciudad_empresa_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
