# Generated by Django 5.2 on 2025-06-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Header', '0009_alter_usuario_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
    ]
